spring:
  application:
    name: geolocation

  datasource:
    url: jdbc:postgresql://localhost:5432/geo_db
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:password}
    ssl:
      enabled: ${SSL_ENABLED:false}
      validate-server-certificate: ${SSL_VALIDATE_CERTIFICATE:false}
    listener:
      simple:
        default-requeue-rejected: false
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 1
          max-interval: 10000

logging:
  level:
    org:
      springframework:
        amqp: debug
